USE MusicArts


CREATE TABLE Genres
(
	GenreId INT PRIMARY KEY IDENTITY,
	GenreName NVARCHAR(50) NOT NULL
)
GO
	GO
CREATE TABLE Countries
(
	CountryId INT PRIMARY KEY IDENTITY,
	CountryName NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE Persons
(
PersonID INT PRIMARY KEY IDENTITY,
LastName NVARCHAR(50),
FirstName NVARCHAR(50),
Birthday DATETIME,
Sex NVARCHAR(20)
)
GO

CREATE TABLE Artists
(
	ArtistId INT PRIMARY KEY IDENTITY,
	GenreID INT NOT NULL FOREIGN KEY  REFERENCES Genres(GenreId),
	CountryID INT NOT NULL FOREIGN KEY  REFERENCES Countries(CountryId),
	PersonID INT FOREIGN KEY REFERENCES Persons(PersonId),
	ArtistSiteUrl NVARCHAR(100)
)
GO
CREATE TABLE Groups
(
	GroupsID INT PRIMARY KEY IDENTITY,
	GroupName NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE GroupArtists
(
GroupId INT  NOT NULL,
ArtistId INT NOT NULL,
GroupRole NVARCHAR(50) NOT NULL,
PRIMARY KEY (GroupId, ArtistId),
CONSTRAINT FK_GroupArtists_GroupId FOREIGN KEY (GroupId) REFERENCES Groups(GroupsID),
CONSTRAINT FK_GroupArtists_ArtistId FOREIGN KEY (ArtistId) REFERENCES Artists(ArtistId)
)
GO


CREATE TABLE Albums
(
	AlbumId INT PRIMARY KEY IDENTITY,
	ArtistId INT NOT NULL FOREIGN KEY REFERENCES Artists(ArtistId),
	AlbumTitle NVARCHAR(50) NOT NULL,
	AlbumYear NVARCHAR(30) NOT NULL,
	AlbumsTracks INT NOT NULL
)
GO

CREATE TABLE Songs
(
	SongId INT PRIMARY KEY IDENTITY,
	SongTitle NVARCHAR(50) NOT NULL,
	SongDuration FLOAT NOT NULL
)
GO

CREATE TABLE AlbumSongs
(
	AlbumId INT NOT NULL FOREIGN KEY REFERENCES Albums(AlbumId),
	SongId INT FOREIGN KEY REFERENCES Songs(SongId),
	TrackNumber INT NOT NULL,
	CONSTRAINT PK_AlbumsSongs PRIMARY KEY (AlbumId, SongId)
)
GO
DROP TABLE Songs
DROP TABLE Artists
DROP TABLE Groups
DROP TABLE Persons
DROP TABLE Countries
DROP TABLE Albums
DROP TABLE Genres
DROP TABLE GroupArtists
DROP TABLE AlbumSongs

